### ISSUE TITLE
Markdown small mistakes

### ISSUE THREAD

**Issue by RicardoSilveira23** [OfficeDev/SharePoint-Add-in-REST-OData-CrossDomain#2]
File: https://github.com/OfficeDev/SharePoint-Add-in-REST-OData-CrossDomain/blob/master/README.md

The title label has an extra hashtag at the end.
![capture](https://user-images.githubusercontent.com/24255374/40067420-feb28790-585d-11e8-9d83-ca0027529d7b.PNG)

The Additional Resources title has an unnecessary tag that is breaking the title formatting.
![capture](https://user-images.githubusercontent.com/24255374/40067504-35fcef88-585e-11e8-85e8-467a5987861a.PNG)

**Comment by Rick-Kirkham** [comment]
Thanks. These are fixed now.
